### ISSUE TITLE
residual connection

### ISSUE THREAD

**Issue by sth4k** [PetarV-/GAT#11]
In GAT/utils/layers.py, for residual, in the else statement, it is "seq_fts = ret + seq".
Shouldn't it be "ret =  ret + seq"?

**Comment by PetarV-** [comment]
Thank you very much for spotting this! Indeed, this went on undetected while porting the code for the public release.

It has been fixed now. :)

**Comment by FrankCAN** [comment]
Hi,
Why is that? Can you please comment some details? how does seq_fts works? As it is already last line.
I modified the code, but the accuracy droped significantly, many thanks for your help.
