### ISSUE TITLE
How did you initialize your model parameters?

### ISSUE THREAD

**Issue by mufeili** [PetarV-/GAT#18]
Hi, thank you for the great work and releasing your code. In the paper you mentioned that the model parameters were initialized with Glorot initialization, but I cannot find it in the code. As I'm not very familiar with TensorFlow, maybe I just missed that part. Could you please elaborate on how did you do this? Thank you!

**Comment by PetarV-** [comment]
Hi,

Thank you for the kind words, and your interest in GAT!

The initialisation is implicit---every layer we have used from `tf.layers` will utilise Glorot (Xavier) initialisation by default, without us having to do anything.

Thanks,
Petar

**Comment by mufeili** [comment]
Got it, thanks a lot! @PetarV-
