### ISSUE TITLE
Encounting a problem while running execute_cora.py

### ISSUE THREAD

**Issue by wanyao1992** [PetarV-/GAT#2]
Dear authors,

Thank you for sharing your source code. When I run this copy of code I encounted the following problem.

"TypeError: unbound method inference() must be called with GAT instance as first argument (got Tensor instance instead)"

I think this problem is caused by that the model instance is not created successfully via "mode = GAT", so I modified this line of code tobe "mode = GAT()", while another bug appeared.

"TypeError: inference() got multiple values for keyword argument 'bias_mat'".

So I am wondering that is this copy of code can be run successfully? My Python version is Python 2.7.13, and with Tensorflow 1.4.0.

**Comment by wanyao1992** [comment]
After I search the internet, I find this may be caused by the Python version I used. I guess that you may use the Python 3. So I will try it again after updating my Python. And you are suggested to add the environment for your implementation in the README file.

**Comment by PetarV-** [comment]
Hi Yao,

You're correct, running the code will require Python 3.

I'll update the readme with the environment requirements in the next few days.

Thanks,
Petar
