### ISSUE TITLE
Pubmed Dataset Accuracy

### ISSUE THREAD

**Issue by mufeili** [PetarV-/GAT#21]
Hi,

I've tried running your code on the Pubmed dataset using the configuration you mentioned in the paper. With `100` runs, the accuracy is about `77.61 +- 0.78` while the paper reports `79.0 +- 0.3`. I'm wondering if you have done some additional modifications as in [the issue about Citeseer accuracy](https://github.com/PetarV-/GAT/issues/14) and it will be great if you can provide these details. Thanks a lot!

**Comment by PetarV-** [comment]
Hi Mufei,

You are correct indeed -- please see #12 .

Thanks,
Petar
