### ISSUE TITLE
Training HyperParameters on Pubmed and Citeseer

### ISSUE THREAD

**Issue by aviczhl2** [PetarV-/GAT#24]
I run the code on Citeseer and pubmed for multiple times and the performance is about 1% lower than expected in paper.
I guess it's because of hyperparameter on these datasets being different from Cora. I'd like to ask which hyperparameters shall be changed to achieve the reported accuracy, thanks.

**Comment by PetarV-** [comment]
Hello,

Please refer to issue #14 for Citeseer and #12 for Pubmed.

Thanks,
Petar

**Comment by aviczhl2** [comment]
Thanks very much for your kind support.
