### ISSUE TITLE
Directed graph or undirected graph?

### ISSUE THREAD

**Issue by Yihan-zz** [PetarV-/GAT#34]
Thank you for your great work but I have a simple question.
Which graph do you think the datasets belongs to? Directed graph or Undirected graph?
In the other words, can we consider a node B as a target node A's neiborhood if there is a link from A to B but not B to A ?

**Comment by PetarV-** [comment]
Hello,

Thank you for your issue and interest in GAT!

All the inputs in the datasets from the paper are undirected, but the GAT model (and our codebase) naturally supports directed edges.

Thanks,
Petar
