### ISSUE TITLE
Method for getting Standard Deviation for Metrics in Report

### ISSUE THREAD

**Issue by akashb95** [PetarV-/GAT#36]
Hi Petar, 

I was wondering if you could tell me how many times you conducted the experiments to get the scores that you reported in your paper? Also, did you run cross-fold validation, and if so, how many folds did you use?

Many thanks,
Akash.

**Comment by PetarV-** [comment]
Hi Akash,

Thank you for your issue and your interest in GAT!

I can confirm we used a single split (standard train/val/test split as normally used for Cora, Citeseer, Pubmed and PPI).

Transductive datasets (Cora, Citeseer, Pubmed) were executed 100 times, while the inductive dataset (PPI) was executed 10 times.

Hope this helps!

Thanks,
Petar
