### ISSUE TITLE
question about attention layer

### ISSUE THREAD

**Issue by caizhenhui** [PetarV-/GAT#39]
HI！
Acccording to paper,Attention only calculated between node's neighboor.I am confused when i see code about "attention_layer", it is calculated on all nodes not only neighboor node?

**Comment by PetarV-** [comment]
Hello,

Thank you for the issue and your interest in GAT!

You are correct that the coefficients are calculated for every node. However, before applying the softmax function, we add the bias_mat, setting all non-edge pairs to "negative infinity" (-1e9). This forces the softmax to assign them a weight of zero, effectively discarding them.

Hope this helps!

Thanks,
Petar

**Comment by caizhenhui** [comment]
Thank you!
