### ISSUE TITLE
I  have a graph ,  how to process the datasets to get x,tx,allx,y,ty,ally,index?

### ISSUE THREAD

**Issue by tanjia123456** [PetarV-/GAT#49]
My datasets is from minboggle, use  the vertices and triangles of the white matter of the right brain to construct a graph, and is this graph three-dimensional.

**Comment by Maulpy** [comment]
Excuse me, How do you solve this?
Thank you very much

**Comment by tanjia123456** [comment]
I still don't know,sorry




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PetarV-/GAT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 下午2:30
收件人:&nbsp;"PetarV-/GAT"<GAT@noreply.github.com&gt;;
抄送:&nbsp;"1248742467"<1248742467@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [PetarV-/GAT] I  have a graph ,  how to process the datasets to get x,tx,allx,y,ty,ally,index? (#49)





 
Excuse me, How do you solve this?
 Thank you very much
