### ISSUE TITLE
how to process the datasets get the .x .y .tx .ty .allx .ally?

### ISSUE THREAD

**Issue by tanjia123456** [PetarV-/GAT#51]
Hi, I'm sorry to bother you
I use mindboggle datasets( Brain structure segmentation, used to divide brain regions).But  i don't konw how to solve the datasets

**Comment by Zer0Credibility** [comment]
This is a pretty domain-specific question -- if you're looking to convert brain images to graphs you'll need a way of generating edges between the brain regions. I don't think mindboggle comes with edges out of the box so you'll need a connectivity map, etc.

**Comment by tanjia123456** [comment]
> 
> 
> This is a pretty domain-specific question -- if you're looking to convert brain images to graphs you'll need a way of generating edges between the brain regions. I don't think mindboggle comes with edges out of the box so you'll need a connectivity map, etc.

I can‘t understand your reply. Does connectivity map mean a graph? I have created a graph by vertice and triangle , but what's format to save it ? I used a command(plt.savefig('HLN-12-1 graph.jpg')) to save it.
