### ISSUE TITLE
ppi

### ISSUE THREAD

**Issue by nnzhan** [PetarV-/GAT#6]
Hi, thanks for sharing the code, could you please provide codes for training ppi data? cuz I see it has a significant improvement over other methods on this dataset.

**Comment by sidneyaraujomelo** [comment]
Code for ppi would be really great, I second that.

**Comment by PetarV-** [comment]
I realised that I left this issue unanswered - I'm sorry.

At this time, we have decided not to include the PPI training script, to avoid overcluttering the repository. However we have provided (in `utils/process_ppi.py`) the script file for preprocessing the data. With its outputs, you should have everything you need (along with appropriate edits to `execute_cora.py`). Should you have any issues with this, please contact me directly.

It should also be noted that our PPI results are no longer state-of-the-art. As far as I know, Gated Attention Networks (GaAN; UAI 2018) hold it at this time:
https://arxiv.org/pdf/1803.07294.pdf
