### ISSUE TITLE
multi-graph node classsification

### ISSUE THREAD

**Issue by tanjia123456** [PetarV-/GAT#61]
@gcucurull @PetarV- 
Hello, I have 20 objects, that is, there are 20 graphs. Now I divide the data set according to graphs, but GAT seems to be able to handle only one graph, and batch-size can only be set to 1. How can I do to process multi-graph node classfication?

**Comment by Yaoyuanzhou** [comment]
我到处都能看到你在提问题，这种问题是实现需求的问题，这个别人咋跟你说嘛，盲猜你非计算机专业而是拿gat来分析你所在学科的数据

**Comment by tanjia123456** [comment]
是滴！哈哈哈不过我已经解决了

**Comment by Yaoyuanzhou** [comment]
嗯嗯，不错，牛皮
