### ISSUE TITLE
What is the difference between GCN and Const-GAT?

### ISSUE THREAD

**Issue by wzm2256** [PetarV-/GAT#9]
Const-GAT is describe as "Const-GAT corresponds to a model with the same architecture as GAT, but with a constant attention mechanism (assigning same importance to each neighbor; GCN-like inductive operator) ".
In my opinion, that is exactly what GCN is.

Could you explain a little bit?

**Comment by wzm2256** [comment]
If what I guess is correct,i.e. Const-GAT is actually GCN, then GAT only surpass the state of the art method by less than 4%, but not some 20% as indicated in the paper. (Then why not comparing with GCN instead? )

**Comment by PetarV-** [comment]
Const-GAT is not quite GCN---the GCN will assign the weight of 1/sqrt(deg(u)deg(v)) for edge u <-> v. Const-GAT will, instead, effectively assign 1/deg(u) for edge u <- v, and 1/deg(v) for edge u -> v.

Critically, we wanted an inductive operator---one that will not be aware of the degrees of neighbours; as in the inductive setting, (test) nodes can be incrementally added into the graph, and hence the degrees may dynamically change.

The purpose of the Const-GAT experiment was, as suggested by one of our reviewers, to directly assess the impact of our attention mechanism, as opposed to our other architectural decisions.

**Comment by wzm2256** [comment]
OK, it's true. I now agree Const_GAT is different from GCN. 
But now I'm wondering why the coefficient stuff could make such a huge difference.

Thanks for your answer and patience.
